service: cloudwatch-slack

useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  region: us-east-1
  memorySize: 512
  timeout: 20
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"
  environment:
    SLACK_SERVICE_ID: ${env:SLACK_SERVICE_ID}

functions:
  cloudwatch_slack:
    handler: dist/lambda.entrypoint
    events:
      - sns: arn:aws:sns:us-east-1:570240163479:devs

package:
  individually: true
  exclude:
    - src/**
    - test/**
    - tsconfig.json
